unified_mode     'true'
name             'rbaioutliers'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-aioutliers'
version          '0.0.11'
