unified_mode     'true'
name             'rbaioutliers'
maintainer       'redborder'
maintainer_email 'malvarez@redborder.com'
license          'All rights reserved'
description      'Installs/Configures cookbook-rb-aioutliers'
version          '0.0.3'
